export const LOGIN_USER_START = "LOGIN_USER_START";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SEARCH_POSTS_START = "SEARCH_POSTS_START";
export const SEARCH_POSTS_ERROR = "SEARCH_POSTS_ERROR";
export const SEARCH_POSTS_COMPLETE = "SEARCH_POSTS_COMPLETE";

export const SEARCH_PHOTOS_START = "SEARCH_PHOTOS_START";
export const SEARCH_PHOTOS_ERROR = "SEARCH_PHOTOS_ERROR";
export const SEARCH_PHOTOS_COMPLETE = "SEARCH_PHOTOS_COMPLETE";

export const SEARCH_DETAIL_START = "SEARCH_DETAIL_START";
export const SEARCH_DETAIL_ERROR = "SEARCH_DETAIL_ERROR";
export const SEARCH_DETAIL_COMPLETE = "SEARCH_DETAIL_COMPLETE";
